import { LegalShell } from "@/components/shared/LegalShell"
import { LEGAL_ENTITY } from "@/lib/legal"

export const metadata = { title: "Terms of Service · Redline" }

const TermsPage = () => (
  <LegalShell title="Terms of Service">
    <section>
      <h2>What Redline is</h2>
      <p>
        Redline is a practice tool operated by {LEGAL_ENTITY} (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;). You describe something you are preparing for, upload supporting
        material, and rehearse against AI-generated interviewers who question you live and
        score the session. It is a simulation built to help you prepare, nothing more.
      </p>
    </section>
    <section>
      <h2>AI output can be wrong</h2>
      <p>
        Everything the panel says, flags, and scores is generated by AI. It can be inaccurate,
        incomplete, or misleading, and it does not constitute professional, legal, financial,
        investment, or compliance advice. Verify anything that matters with a qualified human
        before acting on it. You are responsible for decisions you make based on the service.
      </p>
    </section>
    <section>
      <h2>Your account</h2>
      <p>
        Access is currently invite-only. Keep your sign-in method secure; activity under your
        account is your responsibility. You must be at least 18 to use the service.
      </p>
    </section>
    <section>
      <h2>Your content and the output</h2>
      <p>
        You own what you bring: your ideas, uploads, and what you say in sessions. You grant
        us the limited license needed to operate the service: storing your content, processing
        it with the AI providers listed in the Privacy Policy, and generating your feedback and
        reports. Do not upload material you have no right to share, including other people&apos;s
        confidential information.
      </p>
      <p>
        The transcripts, scores, and reports the service generates for you are yours to keep
        and use. Because they are AI-generated, we do not warrant that they are accurate,
        unique, or free of third-party claims.
      </p>
    </section>
    <section>
      <h2>Acceptable use</h2>
      <p>
        Don&apos;t abuse the service: no attempts to break, overload, or reverse-engineer it, no
        unlawful content, and no using the sessions to generate content that harms others.
      </p>
    </section>
    <section>
      <h2>Your responsibilities and indemnification</h2>
      <p>
        You will indemnify and hold {LEGAL_ENTITY} harmless from claims, damages, and
        reasonable legal costs arising from content you upload without the right to do so,
        your violation of these terms, or your violation of law in using the service.
      </p>
    </section>
    <section>
      <h2>Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;, DURING AN
        INVITED TESTING PERIOD, WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
        THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. We do not warrant that the service will be uninterrupted, error-free,
        or that AI output will be accurate. Features may change or be withdrawn at any time.
      </p>
    </section>
    <section>
      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, {LEGAL_ENTITY} is not liable for indirect,
        incidental, special, or consequential damages, or lost profits, revenue, or data,
        arising from your use of the service. Our total liability for all claims is limited to
        the greater of one hundred U.S. dollars ($100) or the amount you paid us for the
        service in the twelve months before the claim arose. These limits do not apply to
        liability that cannot be limited by law, including liability arising from our gross
        negligence or willful misconduct.
      </p>
    </section>
    <section>
      <h2>Ending things</h2>
      <p>
        You can delete your account and data at any time from Settings. We may suspend or
        terminate accounts that violate these terms. The sections that by their nature
        should outlast termination do so, including Your content and the output,
        Indemnification, Disclaimer of warranties, Limitation of liability, and General.
      </p>
    </section>
    <section>
      <h2>Changes</h2>
      <p>
        We may update these terms; the version date above changes when we do, and continued
        use after a change is acceptance of it. For material changes we will ask you to review
        and accept again.
      </p>
    </section>
    <section>
      <h2>General</h2>
      <p>
        These terms are governed by the laws of the State of Florida, without regard to its
        conflict-of-laws rules, and any dispute will be brought exclusively in the state or
        federal courts located in Florida; you and we each consent to their jurisdiction.
      </p>
      <p>
        These terms and the Privacy Policy are the entire agreement between you and us about
        the service. If any provision is found unenforceable, the rest remain in effect. Our
        not enforcing a provision is not a waiver of it. You may not assign these terms without
        our consent; we may assign them in connection with a merger, acquisition, or sale of
        assets. Neither party is liable for delay or failure caused by events beyond its
        reasonable control.
      </p>
    </section>
    <section>
      <h2>Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a className="underline" href="mailto:development@mediabymayday.com">
          development@mediabymayday.com
        </a>
      </p>
    </section>
  </LegalShell>
)

export default TermsPage
